### ISSUE TITLE
Connecting to a Microsoft SQL server

### ISSUE THREAD

**Issue by jollinshead** [bitnami/bitnami-docker-suitecrm#100]
**Description**

Currently, the `bitnami/suitecrm` image does not include the mssql library and so does not have the capability to connect to a Microsoft SQL server.

After reading the [bitnami documentation "Install Different PHP Modules"](https://docs.bitnami.com/oci/apps/suitecrm/configuration/install-modules-php/#freetds-and-mssql), I attempted to create a docker image but became stuck trying to determine which additional modifications were necessary.

**Possible solution**

With `mssql.so` in the same directory as the `Dockerfile`, here's my Dockerfile so far:

```dockerfile
FROM bitnami/suitecrm:7.11.5

RUN echo "extension=mssql.so" >> /opt/bitnami/php/etc/php.ini

ADD mssql.so /opt/bitnami/php/lib/php/extensions/mssql.so
```

If anyone could provide guidance, help is much appreciated. 

Thank you,
jollinshead

**Comment by tompizmor** [comment]
Hi @jollinshead,

Can you exec into your custom container and run this command?

```
php -m
```

Can you see mssql in the list?

**Comment by jollinshead** [comment]
Hi @tompizmor 

Running `php -m` shows that the `mssql.so` I was using is invalid (probably becuase it compiled in a different environment).
```
/# php -m
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/bitnami/php/lib/php/extensions/mssql.so' - /opt/bitnami/php/lib/php/extensions/mssql.so: invalid ELF header in Unknown on line 0
[PHP Modules]
...
```
I'll try including the compilation steps in the Dockerfile.

**Comment by jollinshead** [comment]
Upon further investigation, the **mssql** driver is [no longer supported](https://php.net/manual/en/intro.mssql.php) in newer versions of PHP. It looks like **sqlsrv** is the one that is required.

I've updated my Dockerfile to build an image that includes the **sqlsrv** driver(s) into the base bitnami-suitecrm image.
```
# Build sqlsrv drivers

FROM php:7.1-apache

ENV ACCEPT_EULA=Y

# Microsoft SQL Server Prerequisites
RUN apt-get update \
    && apt-get install -y gnupg2 \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/9/prod.list \
        > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get install -y --no-install-recommends \
        locales \
        apt-transport-https \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
        unixodbc-dev \
        msodbcsql17

RUN docker-php-ext-install mbstring pdo pdo_mysql \
    && pecl install sqlsrv pdo_sqlsrv xdebug \
    && docker-php-ext-enable sqlsrv pdo_sqlsrv xdebug


# Build suitecrm image

FROM bitnami/suitecrm:7.11.5

RUN apt-get update \
    && apt-get install -y unixodbc-dev

RUN echo "extension=sqlsrv.so" >> /opt/bitnami/php/etc/php.ini && \
    echo "extension=pdo_sqlsrv.so" >> /opt/bitnami/php/etc/php.ini

COPY --from=0 /usr/local/lib/php/extensions/no-debug-non-zts-20160303/sqlsrv.so /opt/bitnami/php/lib/php/extensions/sqlsrv.so
COPY --from=0 /usr/local/lib/php/extensions/no-debug-non-zts-20160303/pdo_sqlsrv.so /opt/bitnami/php/lib/php/extensions/pdo_sqlsrv.so
```

Output of `php -v`:
```
/# php -v
PHP 7.1.30 (cli) (built: May 31 2019 01:14:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.30, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by tompizmor** [comment]
Hi @jollinshead! 

Were you able to connect to the SQL server using that extension? I tried your Dockerfile and it works fine., thanks for sharing it.

**Comment by jollinshead** [comment]
Hi @tompizmor 

Unfortunately, it cannot connect to the server.

My `docker-compose.yml` file looks like:

```
version: '2'

services:
  db:
    image: microsoft/mssql-server-linux:2017-CU8
    restart: on-failure:3
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password
    ports:
      - 31905:1433
    volumes:
      - 'mssql_data:/var/opt/mssql'
  suitecrm:
    image: newly-built-bitnami-suitecrm:latest
    restart: on-failure:3
    environment:
      - MARIADB_HOST=localhost
      - MARIADB_PORT_NUMBER=1433
      - SUITECRM_DATABASE_NAME=suitecrm1
      - SUITECRM_DATABASE_USER=sa
      - SUITECRM_DATABASE_PASSWORD=password
    ports:
      - 31904:80
    volumes:
      - 'suitecrm1_data:/bitnami'

volumes:
  suitecrm1_data:
    driver: local
  mssql_data:
    driver: local
```

...and the suitecrm logs show the app cannot progress past _Trying to connect to MySQL server_:
```
docker-compose logs --follow suitecrm
Attaching to docker_suitecrm_1
suitecrm_1  | 
suitecrm_1  | Welcome to the Bitnami suitecrm container
suitecrm_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-suitecrm
suitecrm_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-suitecrm/issues
suitecrm_1  | 
suitecrm_1  | nami    INFO  Initializing apache
suitecrm_1  | nami    INFO  apache successfully initialized
suitecrm_1  | nami    INFO  Initializing php
suitecrm_1  | nami    INFO  php successfully initialized
suitecrm_1  | nami    INFO  Initializing mysql-client
suitecrm_1  | nami    INFO  mysql-client successfully initialized
suitecrm_1  | nami    INFO  Initializing suitecrm
suitecrm_1  | suitecr INFO  ==> Preparing webserver environment...
suitecrm_1  | suitecr INFO  ==> Preparing PHP environment...
suitecrm_1  | suitecr INFO  ==> Preparing suitecrm environment...
suitecrm_1  | suitecr INFO  ==> Configuring Database...
suitecrm_1  | mysql-c INFO  Trying to connect to MySQL server
```
