### ISSUE TITLE
docker-compose: how to define password for suitecrm db user

### ISSUE THREAD

**Issue by EZS-JD** [bitnami/bitnami-docker-suitecrm#104]
**Description**

I'm trying to customize the standard docker-compose.yml file to suit my needs. I'd like to add a mariadb password for the suitecrm db user supplied in `MARIADB_USER` instead of using `ALLOW_EMPTY_PASSWORD=yes`

I tried setting env-variable MARIADB_PASSWORD but that doesn't seem to be supported (container crashed immediately)

Any help?

**Comment by jotamartos** [comment]
Hi @EZS-JD,

Could you please share with us the docker-compose.yml file you are using? Please note that you will need to set the "MARIADB_PASSWORD" env variable for MariaDB so the database it's created with that password

https://github.com/bitnami/bitnami-docker-mariadb#creating-a-database-on-first-run

and you also need to configure the application with that password (SUITECRM_DATABASE_PASSWORD)

https://github.com/bitnami/bitnami-docker-suitecrm#environment-variables

I hope this information helps.

**Comment by EZS-JD** [comment]
I have tried these steps and the db container crashes immediately.

Here's the docker-compose.yml I've tried:

```
version: '2'
services:
  waermecrm-mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=crmwaerme
      - MARIADB_DATABASE=crmwaerme
      - MARIADB_PASSWORD=password
      - ALLOW_EMPTY_PASSWORD=no
      #- MARIADB_ROOT_USER=root # Default: root
      #- MARIADB_ROOT_PASSWORD=passwort # default: none
    volumes:
      - 'waermecrm-mariadb_data:/bitnami'

    #restart: unless-stopped

    networks:
      - waermecrm

  waermecrm-suitecrm:
    image: 'bitnami/suitecrm:7'
    environment:
      - MARIADB_HOST=waermecrm-mariadb
      - MARIADB_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=crmwaerme
      - SUITECRM_DATABASE_NAME=crmwaerme
      - SUITECRM_DATABASE_PASSWORD=password
      - SUITECRM_USERNAME=admin # default "user"
      - SUITECRM_PASSWORD=password # default "bitnami"
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - '2000:80' # opsone proxy looking at port 2000
      # - '443:443' # don't need https access
    volumes:
      - 'waermecrm-suitecrm_data:/bitnami'
    depends_on:
      - waermecrm-mariadb

    #restart: unless-stopped

    networks:
      - waermecrm

volumes:
  waermecrm-mariadb_data:
    driver: local
  waermecrm-suitecrm_data:
    driver: local

networks:
  waermecrm:
```

**Comment by EZS-JD** [comment]
When running "docker-compose up" I see the error log message:

```
The MARIADB_ROOT_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
crmwaerme_waermecrm-mariadb_1 exited with code 1
```

So I uncommented the two lines

```

      - MARIADB_ROOT_USER=root # Default: root
      - MARIADB_ROOT_PASSWORD=passwort # default: none
```

Now I don't see the previous error message, but still see the line:
`crmwaerme_waermecrm-mariadb_1 exited with code 1`

i.e. the mariadb container still crashes.

**Comment by jotamartos** [comment]
Hi @EZS-JD,

Please remove the containers and volumes and try the following docker-compose.yml file (it's basically the default one but adding the application's database configuration)

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_suitecrm
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_suitecrm
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=bitnami
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - 'mariadb_data:/bitnami'
  suitecrm:
    image: 'bitnami/suitecrm:7'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      - SUITECRM_DATABASE_PASSWORD=bitnami
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'suitecrm_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
```

I tried it and the application didn't return any error and it performed the connection to the database

```
suitecrm_1  | suitecr INFO  ==> Configuring Database...
suitecrm_1  | mysql-c INFO  Trying to connect to MySQL server
suitecrm_1  | mysql-c INFO  Found MySQL server listening at mariadb:3306
suitecrm_1  | mysql-c INFO  MySQL server listening and working at mariadb:3306
```

Let us know if that works for you
