### ISSUE TITLE
Error executing 'postInstallation': EPERM: operation not permitted, symlink '../codeception/codeception/codecept' -> 'codecept'

### ISSUE THREAD

**Issue by diaeddine97** [bitnami/bitnami-docker-suitecrm#110]
**Description**

Hi all, please I kind of stuck in a problem:

**Steps to reproduce the issue:**

1. install docker and docker-compose (OK)
2. Download bitnami/suitecrm and bitnami/mariadb docker compose file using the exact way it's said in the documentation and run it(OK)
3. Trying to change volume destination (host) of suitecrm in docker-compose file to a folder in the home (vm machine), and that folder is shared to host machine (windows). so when I do this, the error in the title above appears, at first there was a db error of permission which got fixed by adding root to mariadb, but for suitecrm, no matter what I do (chown combos, chmod combos , the solutons on net about 1001 and permissions on either the dest folder or /var/lib/docker or even running as root) doesn't work

Please I need some help, I have searched and tested solutions for more than 9 hours, please  maximum tomorrow thanks

**Describe the results you received:**

![Screenshot from 2020-04-30 18-19-58](https://user-images.githubusercontent.com/42179886/80745367-b83d0b00-8b0f-11ea-9d08-76e124d1c04b.png)

**Describe the results you expected:**
I want suitecrm to run like it does when i didn't change volume desttination

**Additional information you deem important (e.g. issue happens only occasionally):**

**Docker-compose**

``` 
version: '2'
services:
  mariadb:
    user: root
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=admin_suitecrm
      - MARIADB_DATABASE=suitecrm
      - MARIADB_PASSWORD=aaaa
      - MARIADB_ROOT_PASSWORD=aaaa
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  suitecrm:
    image: 'bitnami/suitecrm:7'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=admin_suitecrm
      - SUITECRM_DATABASE_NAME=suitecrm
      - SUITECRM_DATABASE_PASSWORD=aaaa
      - SUITECRM_USERNAME=admin
      - SUITECRM_PASSWORD=aaaa
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/home/docker/suitecrm/suitecrm_data:/bitnami/suitecrm'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
```

**Version**

- Output of `docker version`:

```Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683


```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 2
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-26-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 478.1MiB
 Name: docker
 ID: HHQC:VSER:GBKA:ZZNQ:G454:BZ5B:QZNX:YYE5:4YDQ:ECHU:53JI:DE3R
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker used on ubuntu server v20, running on virtualbox  on a windows 10

Thanks for helping
