### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by bf8392** [bitnami/bitnami-docker-suitecrm#121]
Hi, I try to update your container...As the manual states, I only have to change the tag...but if I do so, the container doesn't start anymore...

-> Upgrade from 7.11.15 to latest

What am I doing wrong?

**Comment by marcosbc** [comment]
Hi @bd8392, could you share more information? Like the previous container tag, new tag, full logs, etc.

Note that in 7.11.18 we implemented some major changes with respect to how the SuiteCRM container image initializes, see more here: [7.11.18-debian-10-r13](https://github.com/bitnami/bitnami-docker-suitecrm#71118-debian-10-r13). There you will also find additional notes when upgrading from that version to newer ones.

**Comment by bd8392** [comment]
Hi =) my previous container was 7.11.15...I had autoredeploy activated, why it should update automatically. At the latest tag it failed...Also I have noticed, that the version of suitecrm didn't change with the tag...I'm actually running 7.11.15, but I have the Tag 7.11.17...This is my actual docker-compose (deployed in swarm but onl one machine):

```
version: '3.3'
services:
  suitecrm:
    image: bitnami/suitecrm:7.11.17
    environment:
      MARIADB_HOST: somehost
      MARIADB_PORT_NUMBER: '3306'
      SUITECRM_DATABASE_NAME: someuser
      SUITECRM_DATABASE_PASSWORD: somepass
      SUITECRM_DATABASE_USER: someuser
    volumes:
     - suitecrm_data:/bitnami
    networks:
     - database_stack_net
     - traefik_reverseproxy_net
```

it works now, but the version inside the docker is still 7.11.15...don't know how to update to your latest docker...
