### ISSUE TITLE
Apache 403 after initial install

### ISSUE THREAD

**Issue by ScottAtConvesio** [bitnami/bitnami-docker-suitecrm#141]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------
**Description**

I have setup the `bitnami/suitecrm` docker container using latest image (updated yesterday). I am having the issue described in [https://github.com/bitnami/bitnami-docker-suitecrm/issues/101](https://github.com/bitnami/bitnami-docker-suitecrm/issues/101), but it persists regardless whether `/bitnami` is mounted. Apache gives a 403 error on attempt to access any file or the bare URL. This persists using `curl -I localhost:8080` inside the container. When mounted, I have verified the ownership of the mount point as `daemon:root` I have not run the install, SuiteCRM is running against an existing database.

**Steps to reproduce the issue:**

1. Install `bitnami/suitecrm:latest`
2. access container CLI
3. `curl -I localhost:8080`

**Describe the results you received:**
```
root@vnc-crm:/# curl -I localhost:8080
HTTP/1.1 403 Forbidden
Date: Thu, 04 Nov 2021 12:54:54 GMT
Server: Apache/2.4.51 (Unix) OpenSSL/1.1.1d
Content-Type: text/html; charset=iso-8859-1
```

**Describe the results you expected:**

HTTP status code other than 401 or 403. I presume the login page would show a 200.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
Version:           20.10.9
API version:       1.41
Go version:        go1.16.8
Git commit:        c2ea9bc
Built:             Mon Oct  4 16:08:29 2021
OS/Arch:           linux/amd64
Context:           default
Experimental:      true

Server: Docker Engine - Community
Engine:
Version:          20.10.9
API version:      1.41 (minimum version 1.12)
Go version:       go1.16.8
Git commit:       79ea9d3
Built:            Mon Oct  4 16:06:37 2021
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          1.4.11
GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
runc:
Version:          1.0.2
GitCommit:        v1.0.2-0-g52b36a2
docker-init:
Version:          0.19.0
GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
Context:    default
Debug Mode: false
Plugins:
app: Docker App (Docker Inc., v0.9.1-beta3)
buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
scan: Docker Scan (Docker Inc., v0.8.0)

Server:
Containers: 6
Running: 6
Paused: 0
Stopped: 0
Images: 7
Server Version: 20.10.9
Storage Driver: overlay2
Backing Filesystem: extfs
Supports d_type: true
Native Overlay Diff: true
userxattr: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Cgroup Version: 1
Plugins:
Volume: local
Network: bridge host ipvlan macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
runc version: v1.0.2-0-g52b36a2
init version: de40ad0
Security Options:
apparmor
seccomp
Profile: default
Kernel Version: 5.14.9-051409-generic
Operating System: Ubuntu 20.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.932GiB
Name: dockerhost
ID: GPI2:57UJ:NBLB:7IX2:5PIG:26U5:X53Q:X7TB:O7VZ:RLQ4:NL6N:AJ3H
Docker Root Dir: /var/lib/docker
Debug Mode: false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
n/a
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Vultr VPS, using Portainer for container management

**Comment by ScottAtConvesio** [comment]
Given some of the questions in the related thread, here is output of `docker ps`
```
CONTAINER ID   IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                                                                                     NAMES
73f4e8fb429e   bitnami/suitecrm:latest                 "/opt/bitnami/script…"   17 minutes ago      Up 16minutes       127.0.0.1:8080->8080/tcp, 8443/tcp                                                        suitecrm-vnc
3afa1d2cec3b   vitiman/alpine-icecast:latest           "icecast -c /etc/ice…"   About an hour ago   Up About an hour    0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                                 icecast
ba0f61ab5d60   mariadb:latest                          "docker-entrypoint.s…"   About an hour ago   Up About an hour    0.0.0.0:3306->3306/tcp, :::3306->3306/tcp                                                 mariadb
4b7a593eab99   unclev/prosody-docker-extended:latest   "/usr/bin/entrypoint…"   About an hour ago   Up About a minute   80/tcp, 0.0.0.0:5222->5222/tcp, :::5222->5222/tcp, 443/tcp, 127.0.0.1:5280->5280/tcp, 5281/tcp, 0.0.0.0:5269->5269/tcp, :::5269->5269/tcp, 127.0.0.1:5347->5347/tcp   prosody
f92e6d85bd79   pawelmalak/snippet-box:latest           "docker-entrypoint.s…"   About an hour ago   Up About an hour    127.0.0.1:5000->5000/tcp                                                                  snippet-box
0d206dce8872   portainer/agent:latest                  "./agent"                4 weeks ago         Up 2 weeks          0.0.0.0:9001->9001/tcp, :::9001->9001/tcp                                                 portainer_agent
```
The node is still lightly-loaded. Output of `top`:
```
top - 08:12:50 up 14 days, 23:15,  1 user,  load average: 0.30, 0.21, 0.20
Tasks: 186 total,   1 running, 185 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.7 us,  1.4 sy,  0.0 ni, 95.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   1978.0 total,    178.0 free,    832.2 used,    967.7 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.    941.2 avail Mem
```

**Comment by rafariossaa** [comment]
Hi,
  Are you using the provided docker-compose file ? If you changed any of the parameters, could you indicate those changes ?
  Could you share the logs ?.

**Comment by rprominski** [comment]
It seems like I have the same issue. 
When I am trying to use existing database and passing variable ```SUITECRM_SKIP_BOOTSTRAP=yes``` I can't access suitecrm website, because of 403  error. When I remove that variable from my docker-compose file everything works fine, but of course my configured database is cleared. 
My configuration:

**Docker Version**
```
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:42:59 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:08 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Docker info**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 84
  Running: 0
  Paused: 0
  Stopped: 84
 Images: 513
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-90-generic
 Operating System: Linux Mint 20.1
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.15GiB
 Name: ThinkBook-Mint
 ID: 4J4B:GD4L:WJS6:SMUF:54NG:5GC5:SDMY:VI4M:VW3X:ESJU:AHZC:F3VT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
**docker-compose version**
```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**docker-compose.yml**
```
version: '3'

services:
    suitecrm:
#       image: preconfigured_suitecrm
        image: bitnami/suitecrm:7
        ports: 
            - "8080:8080" 
            - "433:8443" 
        environment:
            - SUITECRM_DATABASE_PASSWORD=$SUITECRM_DATABASE_PASSWORD
            - SUITECRM_DATABASE_HOST=$SUITECRM_DATABASE_HOST
            - SUITECRM_DATABASE_PORT_NUMBER=$SUITECRM_DATABASE_PORT_NUMBER
            - SUITECRM_DATABASE_USER=$SUITECRM_DATABASE_USER
            - SUITECRM_SKIP_BOOTSTRAP=yes
            - SUITECRM_DATABASE_NAME=$SUITECRM_DATABASE_NAME
            - BITNAMI_DEBUG=true              
            - SUITECRM_USERNAME=$SUITECRM_USERNAME
            - SUITECRM_PASSWORD=$SUITECRM_PASSWORD
        volumes:
            - 'suitecrm_data:/bitnami/suitecrm'
        depends_on:
            - suitecrm_mysql
       
    suitecrm_mysql:
#       image: mysql:5.7
        image: preconfigured_suitecrm_mysql
        hostname: $SUITECRM_DATABASE_HOST
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=abc123
volumes:
    suitecrm_data:
        driver: local
```
**docker config**
```
services:
  suitecrm:
    depends_on:
      suitecrm_mysql:
        condition: service_started
    environment:
      BITNAMI_DEBUG: "true"
      SUITECRM_DATABASE_HOST: suitecrm_mysql
      SUITECRM_DATABASE_NAME: bitnami_suitecrm
      SUITECRM_DATABASE_PASSWORD: bitnami
      SUITECRM_DATABASE_PORT_NUMBER: '3306'
      SUITECRM_DATABASE_USER: bn_suitecrm
      SUITECRM_PASSWORD: root123
      SUITECRM_SKIP_BOOTSTRAP: "yes"
      SUITECRM_USERNAME: root
    image: bitnami/suitecrm:7
    ports:
    - published: 8080
      target: 8080
    - published: 433
      target: 8443
    volumes:
    - suitecrm_data:/bitnami/suitecrm:rw
  suitecrm_mysql:
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    hostname: suitecrm_mysql
    image: preconfigured_suitecrm_mysql
    ports:
    - published: 3306
      target: 3306
version: '3'
volumes:
  suitecrm_data:
    driver: local
```
**Logs**
```
suitecrm_1        | suitecrm 10:03:41.56 
suitecrm_1        | suitecrm 10:03:41.56 Welcome to the Bitnami suitecrm container
suitecrm_1        | suitecrm 10:03:41.56 Subscribe to project updates by watching https://github.com/bitnam
i/bitnami-docker-suitecrm
suitecrm_1        | suitecrm 10:03:41.56 Submit issues and feature requests at https://github.com/bitnami/b
itnami-docker-suitecrm/issues
suitecrm_1        | suitecrm 10:03:41.56 
suitecrm_1        | suitecrm 10:03:41.56 INFO  ==> ** Starting SuiteCRM setup **
suitecrm_1        | suitecrm 10:03:41.57 DEBUG ==> Validating settings in APACHE_* environment variables
suitecrm_1        | realpath: /bitnami/apache/conf: No such file or directory
suitecrm_1        | suitecrm 10:03:41.60 INFO  ==> Configuring PHP options
suitecrm_1        | suitecrm 10:03:41.61 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
suitecrm_1        | suitecrm 10:03:41.64 DEBUG ==> Validating settings in SUITECRM_* environment variables.
..
suitecrm_1        | suitecrm 10:03:41.68 INFO  ==> Ensuring SuiteCRM directories exist
suitecrm_1        | suitecrm 10:03:41.69 INFO  ==> Trying to connect to the database server
suitecrm_1        | suitecrm 10:03:41.69 DEBUG ==> Executing SQL command:
suitecrm_1        | SELECT 1
suitecrm_1        | ERROR 2002 (HY000): Can't connect to MySQL server on 'suitecrm_mysql' (115)
suitecrm_1        | suitecrm 10:03:46.70 DEBUG ==> Executing SQL command:
suitecrm_1        | SELECT 1
suitecrm_1        | ERROR 2002 (HY000): Can't connect to MySQL server on 'suitecrm_mysql' (115)
suitecrm_1        | suitecrm 10:03:51.71 DEBUG ==> Executing SQL command:
suitecrm_1        | SELECT 1
suitecrm_1        | ERROR 2002 (HY000): Can't connect to MySQL server on 'suitecrm_mysql' (115)
suitecrm_1        | suitecrm 10:03:56.74 DEBUG ==> Executing SQL command:
suitecrm_1        | SELECT 1
suitecrm_1        | ERROR 2002 (HY000): Can't connect to MySQL server on 'suitecrm_mysql' (115)
suitecrm_1        | suitecrm 10:04:01.75 DEBUG ==> Executing SQL command:
suitecrm_1        | SELECT 1
suitecrm_1        | ERROR 2002 (HY000): Can't connect to MySQL server on 'suitecrm_mysql' (115)
suitecrm_1        | suitecrm 10:04:06.77 DEBUG ==> Executing SQL command:
suitecrm_1        | SELECT 1
suitecrm_1        | 1
suitecrm_1        | suitecrm 10:04:06.78 INFO  ==> An already initialized SuiteCRM database was provided, c
onfiguration will be skipped
suitecrm_1        | suitecrm 10:04:06.78 INFO  ==> Generating SuiteCRM configuration file
suitecrm_1        | suitecrm 10:04:06.80 DEBUG ==> Executing PHP code:
suitecrm_1        | chdir('/opt/bitnami/suitecrm');
suitecrm_1        | define('sugarEntry', true);
suitecrm_1        | require_once('include/utils.php');
suitecrm_1        | 
suitecrm_1        | // Based on 'install.php' includes
suitecrm_1        | require_once('include/SugarLogger/LoggerManager.php');
suitecrm_1        | require_once('sugar_version.php');
suitecrm_1        | require_once('suitecrm_version.php');
suitecrm_1        | require_once('include/TimeDate.php');
suitecrm_1        | require_once('include/Localization/Localization.php');
suitecrm_1        | require_once('include/SugarTheme/SugarTheme.php');
suitecrm_1        | require_once('include/utils/LogicHook.php');
suitecrm_1        | require_once('data/SugarBean.php');
suitecrm_1        | // Include files that are loaded by 'entryPoint.php'
suitecrm_1        | // (Note: We cannot include 'entryPoint.sh' since it is only expected to work via HTTP 
requests)
suitecrm_1        | require_once('include/SugarEmailAddress/SugarEmailAddress.php');
suitecrm_1        | require_once('include/utils/file_utils.php');
suitecrm_1        | 
suitecrm_1        | // Rebuild the configuration file
suitecrm_1        | // Based on the RebuildConfig action in the admin panel
suitecrm_1        | $clean_config = loadCleanConfig();
suitecrm_1        | rebuildConfigFile($clean_config, $sugar_version);
suitecrm_1        | 
suitecrm_1        | // Rebuild the .htaccess file
suitecrm_1        | // Based on the UpgradeAccess action in the admin panel
suitecrm_1        | require_once 'include/upload_file.php';
suitecrm_1        | UploadStream::register();
suitecrm_1        | require('modules/Administration/UpgradeAccess.php');
suitecrm_1        | // This file is based on a config.php file from a completed install. You can obtain it 
by disabling the wizard and browsing to the application.
suitecrm_1        | // This will be used for new installs using existing databases, where we will first use
 a very basic config file and then repair via the app to add missing fields.
suitecrm_1        | PHP Notice:  Trying to access array offset on value of type null in /opt/bitnami/suitec
rm/install/install_utils.php on line 981
suitecrm_1        | PHP Notice:  Trying to access array offset on value of type null in /opt/bitnami/suitec
rm/install/install_utils.php on line 985
suitecrm_1        | suitecrm 10:04:06.86 INFO  ==> Persisting SuiteCRM installation
suitecrm_1        | 
suitecrm_1        | suitecrm 10:04:09.88 INFO  ==> ** SuiteCRM setup finished! **
suitecrm_1        | suitecrm 10:04:09.88 INFO  ==> ** Starting cron **
suitecrm_1        | suitecrm 10:04:09.89 INFO  ==> ** Starting Apache **
suitecrm_1        | [Wed Nov 17 10:04:09.938926 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 se
rver certificate does NOT include an ID which matches the server name
suitecrm_1        | [Wed Nov 17 10:04:09.939240 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 se
rver certificate does NOT include an ID which matches the server name
suitecrm_1        | [Wed Nov 17 10:04:09.960192 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 se
rver certificate does NOT include an ID which matches the server name
suitecrm_1        | [Wed Nov 17 10:04:09.960477 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 se
rver certificate does NOT include an ID which matches the server name
suitecrm_1        | [Wed Nov 17 10:04:09.965805 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.51 (
Unix) OpenSSL/1.1.1d PHP/7.4.25 configured -- resuming normal operations
suitecrm_1        | [Wed Nov 17 10:04:09.965836 2021] [core:notice] [pid 1] AH00094: Command line: '/opt/bi
tnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
suitecrm_1        | 172.27.0.1 - - [17/Nov/2021:10:04:40 +0000] "GET / HTTP/1.1" 403 199
suitecrm_1        | 172.27.0.1 - - [17/Nov/2021:10:04:40 +0000] "GET /favicon.ico HTTP/1.1" 403 199
suitecrm_1        | 172.27.0.1 - - [17/Nov/2021:10:04:40 +0000] "GET / HTTP/1.1" 403 199
suitecrm_1        | 172.27.0.1 - - [17/Nov/2021:10:04:40 +0000] "GET /favicon.ico HTTP/1.1" 403 199
suitecrm_1        | 172.27.0.1 - - [17/Nov/2021:10:04:41 +0000] "GET / HTTP/1.1" 403 199
suitecrm_1        | 172.27.0.1 - - [17/Nov/2021:10:04:41 +0000] "GET /favicon.ico HTTP/1.1" 403 199
suitecrm_1        | 172.27.0.1 - - [17/Nov/2021:10:04:41 +0000] "GET / HTTP/1.1" 403 199
suitecrm_1        | 172.27.0.1 - - [17/Nov/2021:10:04:41 +0000] "GET /favicon.ico HTTP/1.1" 403 199
```
