### ISSUE TITLE
SUITECRM_HOST does not appear to be working

### ISSUE THREAD

**Issue by mckinnon81** [bitnami/bitnami-docker-suitecrm#145]
### Name and Version

docker.io/bitnami/suitecrm:latest

### What steps will reproduce the bug?

Using docker-compose with the following config 

```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_suitecrm
      - MARIADB_DATABASE=bitnami_suitecrm
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  suitecrm:
    image: docker.io/bitnami/suitecrm:latest
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - SUITECRM_DATABASE_HOST=mariadb
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      - SUITECRM_HOST=crm.mysite.com
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'suitecrm_data:/bitnami/suitecrm'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
```

After using the search on the top tool bar it prodeces the results. But hovering of the list shows **localhost** as the fqdn. Not what SUITECRM_HOST has been specified as. config.php shows site_url as http://localhost

### What is the expected behavior?

config.php site_url should be updated with SUITECRM_HOST variable. 

When using the searchn function, the fqdn should be used. Not localhost. 

### What do you see instead?

When hovering of the links, fqdn show localhost.
