### ISSUE TITLE
Docker Compose refuses connections

### ISSUE THREAD

**Issue by OSXGroupFL** [bitnami/bitnami-docker-suitecrm#150]
### Name and Version

Suite-Crm

### What steps will reproduce the bug?

Ubuntu 20.04
Latest Docker packages w/Compose
curl -i ip:9090 
curl: (7) Failed to connect to 127.0.0.1 port 9090: Connection refused

### What is the expected behavior?

Return a suitecrm page

### What do you see instead?
```
curl: (7) Failed to connect to 127.0.0.1 port 9090: Connection refused
```
### Additional information

`docker-compose up -d` runs with no issue
`lsof` shows docker listening: 
```console
docker-pr 386945 root    4u  IPv4 2463918      0t0  TCP *:9443 (LISTEN)
docker-pr 386954 root    4u  IPv6 2463925      0t0  TCP *:9443 (LISTEN)
docker-pr 386982 root    4u  IPv4 2461432      0t0  TCP *:9090 (LISTEN)
docker-pr 386991 root    4u  IPv6 2461437      0t0  TCP *:9090 (LISTEN)
```
Compose File I'm running minus passwords and URL:
```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_suitecrm
      - MARIADB_DATABASE=bitnami_suitecrm
      - MARIADB_PASSWORD=******
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  suitecrm:
    image: docker.io/bitnami/suitecrm:8
    ports:
      - '9090:8080'
      - '9443:8443'
    environment:
      - SUITECRM_DATABASE_HOST=mariadb
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      - SUITECRM_DATABASE_PASSWORD=********
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # ALLOW_EMPTY_PASSWORD=yes
      - SUITECRM_HOST=crm.***********.com
    volumes:
      - 'suitecrm_data:/bitnami/suitecrm'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
```
