### ISSUE TITLE
Cannot launch container with `SUITECRM_HOST` parameter

### ISSUE THREAD

**Issue by sameersbn** [bitnami/bitnami-docker-suitecrm#18]
When I launch container with `SUITECRM_HOST` parameter, the container initialization fails with the following logs:

```
application_1  | nami    INFO  Initializing apache
application_1  | apache  INFO  ==> Patching httpoxy...
application_1  | nami    INFO  apache successfully initialized
application_1  | nami    INFO  Initializing suitecrm
application_1  | suitecr INFO  Preparing webserver environment...
application_1  | suitecr INFO  Preparing PHP environment...
application_1  | suitecr INFO  Preparing suitecrm environment...
application_1  | suitecr INFO  Configuring Database...
application_1  | mysqlCo INFO  Trying to connect to MySQL server
application_1  | mysqlCo INFO  Found MySQL server listening at mariadb:3306
application_1  | mysqlCo INFO  MySQL server listening and working at mariadb:3306
application_1  | suitecr INFO  Configuring silent installation
application_1  | suitecr INFO  Configuring SMTP...
application_1  | suitecr INFO  Installing suitecrm. It could take some minutes...
application_1  | Error executing 'postInstallation': Error trying to install the application
```

The following `docker-compose.yaml` file can be used to reproduce the issue

```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  application:
    image: 'bitnami/suitecrm:latest'
    ports:
      - '10080:80'
      - '10443:443'
    volumes:
      - 'suitecrm_data:/bitnami/suitecrm'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
    depends_on:
      - mariadb
    environment:
      - SUITECRM_HOST=suite.example.com
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
```
