### ISSUE TITLE
Container initialization fails if SMTP parameters are specified

### ISSUE THREAD

**Issue by sameersbn** [bitnami/bitnami-docker-suitecrm#41]
If the SMTP configuration is specified at the time of launching the container, the container initialisation sequence errors out with the output:

```console
suitecrm_1  | 
suitecrm_1  | Welcome to the Bitnami suitecrm container
suitecrm_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-suitecrm
suitecrm_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-suitecrm/issues
suitecrm_1  | Send us your feedback at containers@bitnami.com
suitecrm_1  | 
suitecrm_1  | nami    INFO  Initializing apache
suitecrm_1  | apache  INFO  ==> Patching httpoxy...
suitecrm_1  | nami    INFO  apache successfully initialized
suitecrm_1  | nami    INFO  Initializing php
suitecrm_1  | nami    INFO  php successfully initialized
suitecrm_1  | nami    INFO  Initializing suitecrm
suitecrm_1  | suitecr INFO  Preparing webserver environment...
suitecrm_1  | suitecr INFO  Preparing PHP environment...
suitecrm_1  | suitecr INFO  Preparing suitecrm environment...
suitecrm_1  | suitecr INFO  Configuring Database...
suitecrm_1  | mysqlCo INFO  Trying to connect to MySQL server
suitecrm_1  | mysqlCo INFO  Found MySQL server listening at mariadb:3306
suitecrm_1  | mysqlCo INFO  MySQL server listening and working at mariadb:3306
suitecrm_1  | suitecr INFO  Configuring silent installation
suitecrm_1  | suitecr INFO  Configuring SMTP...
suitecrm_1  | suitecr INFO  Installing suitecrm. It could take some minutes...
suitecrm_1  | Error executing 'postInstallation': Server returned status code 500 from http://127.0.0.1/index.php?action=index&module=Home&record=1
suitecrm_1  | Server returned status code 500 from http://127.0.0.1/index.php?action=index&module=Home&record=1
``` 

I used the following `docker-compose.yml` file to create the container:

```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'suitecrm_data:/bitnami/suitecrm'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
    depends_on:
      - mariadb
    environment:
      - SUITECRM_SMTP_HOST=smtp.gmail.com
      - SUITECRM_SMTP_USER=your_email@gmail.com
      - SUITECRM_SMTP_PASSWORD=your_password
      - SUITECRM_SMTP_PROTOCOL=TLS
      - SUITECRM_SMTP_PORT=587
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
```
