### ISSUE TITLE
data persistence

### ISSUE THREAD

**Issue by thenewguy** [bitnami/bitnami-docker-suitecrm#62]
This issue is similar to https://github.com/bitnami/bitnami-docker-suitecrm/issues/58 except that it works normally unless I attempt to use host directories as data volumes as described in the documentation here: https://github.com/bitnami/bitnami-docker-suitecrm#mount-host-directories-as-data-volumes-with-docker-compose

I created a new issue because it doesn't seem to be the same problem although the error message is the same.

Can you please post a docker compose file that works from an not yet installed state?  On Ubuntu 16.04, suitecrm cannot write to the suitecrm directory link.

Any alternate form of data persistence that can be easily backed up as a workaround would be appreciated 

This is the compose file I am using:
```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/data/deploy/volumes/mariadb/mariadb:/bitnami/mariadb'
  suitecrm:
    image: 'bitnami/suitecrm:7.9.4-r0'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/data/deploy/volumes/suitecrm/suitecrm:/bitnami/suitecrm'
      - '/data/deploy/volumes/suitecrm/apache:/bitnami/apache'
      - '/data/deploy/volumes/suitecrm/php:/bitnami/php'
    links:
      - mariadb
```

Apache and php directories are used:
```
$ ls -l /data/deploy/volumes/suitecrm/apache/
total 4
drwxr-xr-x 6 root root 4096 Jul 21 16:01 conf


$ ls -l /data/deploy/volumes/suitecrm/php/
total 4
drwxr-xr-x 3 root root 4096 Jul 21 16:01 conf


$ ls -l /data/deploy/volumes/suitecrm/suitecrm/
total 0


$ ls -ld /data/deploy/volumes/suitecrm/*
drwxr-xr-x 3 root root 4096 Jul 21 16:01 /data/deploy/volumes/suitecrm/apache
drwxr-xr-x 3 root root 4096 Jul 21 16:01 /data/deploy/volumes/suitecrm/php
drwxr-xr-x 2 root root 4096 Jul 21 16:01 /data/deploy/volumes/suitecrm/suitecrm

```

**Comment by sameersbn** [comment]
First of please note that `links` is deprecated in docker-compose v2.
Secondly, since the `7.9.2-r1` release you can mount a single volume at `/bitnami` path for persistence. You no longer need to mount 3 different volumes (php, apache and suitecrm). However you can continue to mount 3 volumes if it suits your use-case.

With these changes, below is a working docker-compose.yml file. If you continue to see issues, please share details of your docker setup? f.e. output of `docker version`, `docker info`, host distro (ubuntu/centos/etc), docker 4 mac, etc. 

```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/data/deploy/volumes/mariadb:/bitnami'
  suitecrm:
    image: 'bitnami/suitecrm:7.9.4-r0'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/data/deploy/volumes/suitecrm:/bitnami'
    depends_on:
      - mariadb
```

**Comment by sameersbn** [comment]
Please take a look at my comment in https://github.com/bitnami/bitnami-docker-suitecrm/issues/58#issuecomment-318327187. Maybe it could help resolve this issue as well.

**Comment by thenewguy** [comment]
@sameersbn can you post the ownership for the directories and confirm that suitecrm was able to write? Using latest versions of docker and compose. The Host system is a VM dedicated to running suitecrm. What host operating system and version are you running? What permissions are set for the host side of the links?

**Comment by sameersbn** [comment]
**Update**: 

I tried the docker-compose.yml file on a ubuntu 14.04 vm and am seeing the issue. I am in the process of debugging it and will let you know the results shortly. /cc @dbarranco @andresbono

**Comment by sameersbn** [comment]
False alarm!

I noticed only one instance where the mariadb container did not start. So the error occurred as expected.  I haven't been able to reproduce it again. 

**Environment**:
  - Host: Ubuntu 16.04.2 LTS (up-to-date) running in a VirtualBox VM.
  - Docker version: 17.05.0-ce (installed using https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/)
  - Compose version: 1.15.0 `installed with pip install -U docker-compose`

**Docker Compose Manifest:**

```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/data/deploy/volumes/mariadb:/bitnami'
  suitecrm:
    image: 'bitnami/suitecrm:7.9.4-r0'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/data/deploy/volumes/suitecrm:/bitnami'
    depends_on:
      - mariadb
```

**Steps**

SSH into VM and create the docker-compose.yml file as listed above

```bash
$ docker-compose up
```

Visit http://localhost to access the application

**Requested Details (https://github.com/bitnami/bitnami-docker-suitecrm/issues/62#issuecomment-318352127)**

```bash
sameersbn@sameersbn-VirtualBox:~$ ls -l /data/deploy/volumes/suitecrm/apache/
total 4
drwxr-xr-x 6 root root 4096 Jul 28 13:56 conf
sameersbn@sameersbn-VirtualBox:~$ ls -l /data/deploy/volumes/suitecrm/php/
total 4
drwxr-xr-x 3 root root 4096 Jul 28 13:56 conf
sameersbn@sameersbn-VirtualBox:~$ ls -l /data/deploy/volumes/suitecrm/suitecrm/
total 64
drwxr-xr-x  15 daemon daemon  4096 Jul 28 14:00 cache
-rw-r--r--   1 daemon daemon   160 Jul 28 13:58 config_override.php
-rw-r--r--   1 daemon daemon 10086 Jul 28 13:59 config.php
drwxr-xr-x   6 daemon daemon  4096 Jul 28 13:58 custom
drwxr-xr-x   3 daemon daemon  4096 Jul 28 13:59 data
drwxr-xr-x  58 daemon daemon  4096 Jul 28 13:58 include
drwxr-xr-x   6 daemon daemon  4096 Jul 28 13:59 install
-rw-r--r--   1 daemon daemon     0 Jul 28 13:58 manifest.php
drwxr-xr-x   2 daemon daemon  4096 Jul 28 13:59 metadata
drwxr-xr-x   3 daemon daemon  4096 Jul 28 13:58 ModuleInstall
drwxr-xr-x 112 daemon daemon  4096 Jul 28 13:58 modules
-rw-r--r--   1 daemon daemon     0 Jul 28 13:59 suitecrm.log
drwxr-xr-x   6 daemon daemon  4096 Jul 28 13:59 themes
drwxr-xr-x   2 daemon daemon  4096 Jul 28 13:59 upload
drwxr-xr-x   2 daemon daemon  4096 Jul 28 13:59 XTemplate
drwxr-xr-x   8 daemon daemon  4096 Jul 28 13:58 Zend
```

**Comment by sameersbn** [comment]
If you can provide specific details about your environment, it'll allow us to duplicate and resolve the issue. Thanks

**Comment by thenewguy** [comment]
Installation was successful with the new compose file you provided:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/data/deploy/volumes/mariadb:/bitnami'
  suitecrm:
    image: 'bitnami/suitecrm:7.9.4-r0'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/data/deploy/volumes/suitecrm:/bitnami'
    depends_on:
      - mariadb

```

This is host os information requested:

```
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-87-generic x86_64)

$ uname -a
Linux CRM 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ sudo docker --version
Docker version 17.05.0-ce, build 89658be

$ sudo docker-compose --version
docker-compose version 1.13.0, build 1719ceb

```


This is very good news.  Thank you for the help
