### ISSUE TITLE
Can't connect to MariaDB

### ISSUE THREAD

**Issue by kiselevo** [bitnami/bitnami-docker-suitecrm#71]
Can't connect to MariaDB:

suitecrm_1 | Welcome to the Bitnami suitecrm container
suitecrm_1 | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-suitecrm
suitecrm_1 | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-suitecrm/issues
suitecrm_1 | Send us your feedback at containers@bitnami.com
suitecrm_1 |
mariadb_1  | INFO  ==> Starting mariadb...
mariadb_1  | INFO  ==> Starting mysqld_safe...
mariadb_1  | 171204 18:55:35 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
mariadb_1  | 171204 18:55:35 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
suitecrm_1 | nami    INFO  Initializing suitecrm
suitecrm_1 | suitecr INFO  Preparing webserver environment...
suitecrm_1 | suitecr INFO  Preparing PHP environment...
suitecrm_1 | suitecr INFO  Preparing suitecrm environment...
suitecrm_1 | suitecr INFO  Configuring Database...
suitecrm_1 | mysql-c INFO  Trying to connect to MySQL server
suitecrm_1 | mysql-c INFO  Found MySQL server listening at localhost:3306
suitecrm_1 | mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
suitecrm_1 | mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
suitecrm_1 | mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
suitecrm_1 | mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
suitecrm_1 | mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
suitecrm_1 | Error executing 'postInstallation': Cannot connect to MySQL server:
suitecrm_1 | MySQL command failed to run. Error:
suitecrm_1 |  ERROR 2002 (HY000): Can't connect to local MySQL server through socket  (2 "No such file or directory")
suitecrm_1 |
suitecrm_suitecrm_1 exited with code 1

There is no path '/opt/bitnami/mysql/tmp/mysql.sock' in MariaDB docker container.
MariaDB socket file located on another path:

/opt/bitnami/**mariadb**/tmp/mysql.sock

**Comment by juan131** [comment]
Hi @kiselevo I noticed you closed the issue. Did you already solved your problem?

**Comment by derroman** [comment]
I'm encountering the same issue and some advice would be helpful

**Comment by juan131** [comment]
Hi @derroman 

What steps did you follow? 
Did you change anything on the configuration or did you just run `docker-compose` up? 
Could you please provide us the information to reproduce the issue?

**Comment by derroman** [comment]
actually I've only wanted to run mariadb on a different port than 3306 (3307 in my example). here'Se the config I've used

`version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=##FANCYPASSWORD##
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3307
    ports:
      - '3307:3307'
    volumes:
      - '/srv/suitecrm/mariadb-persistence:/bitnami'
    networks:
        - suitecrm-tier
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '9090:80'
      - '9091:443'
    environment:
      - SUITECRM_USERNAME=admin
      - SUITECRM_PASSWORD=##YETANOTHERPASSWORD##
      - SUITECRM_EMAIL=me@fancy.com
      - MARIADB_USER=root
      - MARIADB_PASSWORD=##FANCYPASSWORD##
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3307
      - SUITECRM_SMTP_HOST=smtp.gmail.com
      - SUITECRM_SMTP_USER=info@gmail
      - SUITECRM_SMTP_PASSWORD=##ANOTHERFANCYPASSWORD##
      - SUITECRM_SMTP_PROTOCOL=TLS
      - SUITECRM_SMTP_PORT=587
    volumes:
      - '/srv/suitecrm/suitecrm-persistence:/bitnami'
    depends_on:
      - mariadb
    networks:
      - suitecrm-tier
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
networks:
  suitecrm-tier:
    external: true`

**Comment by kiselevo** [comment]
Hi,

I resolved the issue by changing MariaDB to Mysql and defined the Bridge networks:
Below is a working Docker-compose.yml:

version: '2'

networks:
  app-tier:
    driver: bridge
    
services:
  mysql:
    image: 'bitnami/mysql:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    volumes:
      - './db:/bitnami'
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    networks:
      - app-tier
    environment:
      - MARIADB_HOST=mysql
    depends_on:
      - mysql
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './app:/bitnami'ADB_HOST=localhost
      - MARIADB_USER=root
      - MARIADB_PASSWORD=root
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './app:/bitnami'

**Comment by derroman** [comment]
unfortunately this does not help at all, @kiselevo 

My problem is, I want to have another (maria)db port instead of 3306.

**Comment by juan131** [comment]
Hello @derroman 

I used the `docker-compose.yml` file below and I was able to deploy a successful `docker-compose up`. As you'd notice I just modified the `MARIADB_ROOT_PORT`, it's not necessary to modify the host:

```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_PORT_NUMBER=3307
      - MARIADB_ROOT_PASSWORD=FANCYPASSWORD
    volumes:
      - 'mariadb_data:/bitnami'
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'suitecrm_data:/bitnami'
    environment:
      - MARIADB_PORT_NUMBER=3307
      - MARIADB_PASSWORD=FANCYPASSWORD
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
```

Did you have a "clean" Docker environment? Run `docker-compose down -v --rmi 'all'` to have it.
