### ISSUE TITLE
Mariadb volume data dir needs 777 to work

### ISSUE THREAD

**Issue by RobinEd** [bitnami/bitnami-docker-suitecrm#72]
if you want a persistent database outside of the docker image, /var/lib/docker/volumes/mariadb_data/_data/ needs to be 777! Otherwise you get the following error when bringing the container up:
mariadb_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mariadb'

**Steps to reproduce the issue:**
NB running as a system user, not as root user!

1. create volume
docker volume create --label mariadb_data --name mariadb_data
2. docker-compose.yml
```
version: '2'

networks:
  suitecrm-tier:
    driver: bridge

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=ag63hxfd44SS3h66
    volumes:
      - '/var/lib/docker/volumes/mariadb_data/_data:/bitnami'
    networks:
      - suitecrm-tier
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    environment:
      - MARIADB_PASSWORD=ag63hxfd44SS3h66
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/lib/docker/volumes/suitecrm_data/_data:/bitnami'
    networks:
      - suitecrm-tier
```
3. docker-compose up

**Describe the results you received:**

mariadb_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mariadb'

the mariadb image goes up without an error

**Additional information you deem important (e.g. issue happens only occasionally):**

chmod 777 /var/lib/docker/volumes/mariadb_data/_data/

then the docker image will go up

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:35:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:45:06 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

- Output of `docker info`:

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 0
Server Version: 17.11.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.5.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797GiB
Name: suitecrm.edgarbv.int
ID: XMMD:ADXC:EDOO:7XP5:5GCD:IBKQ:TK4X:NQDW:Y27A:MNKF:I5NC:NODW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build 6d101fb
docker-py version: 2.6.1
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
This is running on CentOS 7 64 bit in a vmware esxi 6.5 VM

**Comment by dbarranco** [comment]
Hi @RobinEd 

I am afraid that you can not set a full path in the volume unless you have changed the owner/permissions of that directory. This is not an issue of the Bitnami images, it's the default behaviour of Docker. You have more information about that [here](https://github.com/moby/moby/issues/2259).

But if your intention is to have in `/var/lib/docker/volumes/whatever` the persistent volumes of your containers you can use this:

* Create the volumes: 
`docker volume create --label mariadb_data --name mariadb_data`
`docker volume create --label suitecrm_data --name suitecrm_data`

* Reference those volumes as `external` drivers in your docker-compose:

```
version: '2'

networks:
  suitecrm-tier:
    driver: bridge

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami'
    networks:
      - suitecrm-tier
    environment:
      - MARIADB_ROOT_PASSWORD= ag63hxfd44SS3h66
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'suitecrm_data:/bitnami'
    networks:
      - suitecrm-tier
    environment:
      - MARIADB_PASSWORD= ag63hxfd44SS3h66

volumes:
  mariadb_data:
    external:
      name: mariadb_data
  suitecrm_data:
    external:
      name: suitecrm_data
```

In that way, the volumes that are created won't follow the naming convention of docker-compose (using as prefix the folder in which you have the docker-compose, [information about that here](https://forums.docker.com/t/docker-compose-prepends-directory-name-to-named-volumes/32835/4)) and will use the ones you have created:

```
bitnami@ ~ () $ docker volume ls
DRIVER              VOLUME NAME
local               mariadb_data
local               suitecrm_data
```

Also, if you inspect the container once deployed to see where are the volumes mounted with `docker inspect bitnami_mariadb_1`, you will see the following:

```
"Mounts": [
            {
                "Type": "volume",
                "Name": "mariadb_data",
                "Source": "/var/lib/docker/volumes/mariadb_data/_data",
                "Destination": "/bitnami",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            }
```

So it has the correct path that you want. The folder `_data` is automatically created by Docker.


May this be what you are looking for? 

Best regards.

**Comment by RobinEd** [comment]
Thanks for the explanation! I am puzzled though why giving the full path does work for the suitecrm volume - I don't need to change permissions there?

**Comment by sameersbn** [comment]
@RobinEd Please update you're docker-compose.yml to

```yaml
version: '2'

networks:
  suitecrm-tier:
    driver: bridge

services:
  fix-mariadb-permissions:
    image: 'bitnami/mariadb:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - '/var/lib/docker/volumes/mariadb_data/_data:/bitnami'
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=ag63hxfd44SS3h66
    volumes:
      - '/var/lib/docker/volumes/mariadb_data/_data:/bitnami'
    networks:
      - suitecrm-tier
    depends_on:
      - fix-mariadb-permissions
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    environment:
      - MARIADB_PASSWORD=ag63hxfd44SS3h66
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/lib/docker/volumes/suitecrm_data/_data:/bitnami'
    networks:
      - suitecrm-tier
```

The issue is, the bitnami/mariadb image now uses a non-root approach to start processes in a container. This is done to enhance the security. But unfortunately a side effect of this is that we're no longer able to correct any file permission issues automatically, thereby requiring users to explicitly set the ownership of the data volume.

The above workaround basically is another take at this required manual step while using host mounted volumes to fix the ownership of the data volume.

**Comment by sameersbn** [comment]
ps. I would advise against mounting your volume from `/var/lib/docker/`

**Comment by dbarranco** [comment]
Hi @RobinEd 

The SuiteCRM container won't fail because the user that is running the installer of SuiteCRM is `root`. In the MariaDB container, we changed this approach to not to user the `root` user as the default user in the container, for security concerns. [Changelog including the change of approach](https://github.com/bitnami/bitnami-docker-mariadb#10128-r2).

Indeed, you could use the previous docker-compose you shared but adding the `user: root` key:

```
version: '2'

networks:
  suitecrm-tier:
    driver: bridge

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    user: root
    environment:
      - MARIADB_ROOT_PASSWORD=ag63hxfd44SS3h66
    volumes:
      - '/var/lib/docker/volumes/mariadb_data/_data:/bitnami'
    networks:
      - suitecrm-tier
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    environment:
      - MARIADB_PASSWORD=ag63hxfd44SS3h66
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/lib/docker/volumes/suitecrm_data/_data:/bitnami'
    networks:
      - suitecrm-tier
```

And this would work, and you will also have the volume name you're looking for:

```
bitnami@ ~ () $ docker volume ls
DRIVER              VOLUME NAME
local               bitnami_suitecrm_data
local               mariadb_data
```

So it seems Docker admit full path to the volumes, that's my mistake, sorry.

So you can now choose which is the best approach for you, having the container executed by root or the non-root approach. 
Best regards.
